### ISSUE TITLE
Cannot find module .../node_modules/@nestjs/graphql/dist/schema-builder/storages/lazy-metadata.storage

### ISSUE THREAD

**Issue by GP4cK** [TriPSs/nestjs-query#480]
**Describe the bug**

I get this error after upgrading to the latest version of @nestjs/graphql:

```
Error: Cannot find module '.../node_modules/@nestjs/graphql/dist/schema-builder/storages/lazy-metadata.storage'
at createEsmNotFoundErr (node:internal/modules/cjs/loader:1493:15)
at finalizeEsmResolution (node:internal/modules/cjs/loader:1482:9)
at resolveExports (node:internal/modules/cjs/loader:685:14)
at Module._findPath (node:internal/modules/cjs/loader:752:31)
at Module._resolveFilename (node:internal/modules/cjs/loader:1441:27)
at defaultResolveImpl (node:internal/modules/cjs/loader:1066:19)
at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1071:22)
at Module._load (node:internal/modules/cjs/loader:1242:25)
at wrapModuleLoad (node:internal/modules/cjs/loader:255:19)
at Module.require (node:internal/modules/cjs/loader:1556:12) {
code: 'MODULE_NOT_FOUND',
}
```

The problem is that this package depends on private files from @nestjs/graphql which are no longer available.
See: https://github.com/TriPSs/nestjs-query/blob/2bc913ada5ec62df54b7fca91a521adb31e51b9f/packages/query-graphql/src/common/external.utils.ts#L30

### Have you read the [Contributing Guidelines](https://github.com/tripss/nestjs-query/blob/master/CONTRIBUTING.md)?

Yes

**To Reproduce**
1. Upgrade to  @nestjs/graphql@13.4.1
2. Get the error

**Expected behavior**
No error

**Comment by GP4cK** [comment]
Opus tells me the root cause is @nestjs/graphql@13 introduced an exports map in its package.json. That switches Node's resolver to strict ESM-style behavior, which does not auto-append .js to deep paths. The file lazy-metadata.storage.js exists, but the import asks for lazy-metadata.storage (no extension), and the ./* wildcard maps that literally.

A hack would be to do append `.js` to the import:
```ts
// before
import { LazyMetadataStorage } from '@nestjs/graphql/dist/schema-builder/storages/lazy-metadata.storage'
// after
import { LazyMetadataStorage } from '@nestjs/graphql/dist/schema-builder/storages/lazy-metadata.storage.js'
```

I dug more:
Looking at the actual use — it's a single call site at field-comparison.factory.ts:70. nestjs-query needs the enum's registered name to build a <EnumName>FilterComparison type. It calls LazyMetadataStorage.load() because createFilterComparisonType runs at decorator-evaluation time (when @FilterableField is processed on the DTO), which is before Nest bootstraps and triggers @nestjs/graphql's own lazy loaders.

So LazyMetadataStorage.load() is a timing hack, not an information hack. Three architecturally cleaner options, ranked by effort:

1. Defer filter-type creation to schema-build time (cleanest)
Instead of generating the filter comparison input at decorator time, register a deferred factory that runs when GraphQLSchemaFactory builds the schema. By then @nestjs/graphql has loaded all enums into the public TypeMetadataStorage, so TypeMetadataStorage.getEnumsMetadata() works on its own — no deep import. This mirrors the pattern @nestjs/graphql itself uses (which is why LazyMetadataStorage exists internally). Larger refactor.

2. Lift the lookup to onModuleInit of NestjsQueryGraphQLModule
Keep most code untouched, but the few paths that need enum names walk known DTOs once at module init and resolve their filter types then. By that lifecycle phase, TypeMetadataStorage is already populated by Nest's own bootstrap — no LazyMetadataStorage needed. Medium refactor.

3. Parallel enum registry inside nestjs-query
Re-export a wrapper around registerEnumType that also stores { enum → name } in nestjs-query's own map. Users would have to switch their import to the wrapper for enums used in filters. Smaller code change but a breaking API change for consumers.

**Comment by northvik** [comment]
## `MODULE_NOT_FOUND` with `@nestjs/graphql` >= 13.x — extensionless `require` in `external.utils.js`

In `@ptc-org/nestjs-query-graphql@9.4.0`, the file `src/common/external.utils.js` (line 8) does:

```js
const lazy_metadata_storage_1 = require("@nestjs/graphql/dist/schema-builder/storages/lazy-metadata.storage");
```

This require path is missing the `.js` extension. Since `@nestjs/graphql` >= 13.x defines an `exports` map with `"./*": "./*"` in its `package.json`, Node's CJS subpath resolution does **not** auto-append `.js` when resolving through the exports map, resulting in:

```
Error: Cannot find module '.../node_modules/@nestjs/graphql/dist/schema-builder/storages/lazy-metadata.storage'
    code: 'MODULE_NOT_FOUND'
```

The fix is a one-character change — append `.js` to the require path:

```diff
- const lazy_metadata_storage_1 = require("@nestjs/graphql/dist/schema-builder/storages/lazy-metadata.storage");
+ const lazy_metadata_storage_1 = require("@nestjs/graphql/dist/schema-builder/storages/lazy-metadata.storage.js");
```

**Workaround**: We are currently applying this via a `sed` command in our Docker build:

```sh
sed -i 's|lazy-metadata.storage"|lazy-metadata.storage.js"|' \
    node_modules/@ptc-org/nestjs-query-graphql/src/common/external.utils.js
```

**Reproduction**: Install `@ptc-org/nestjs-query-graphql@9.4.0` + `@nestjs/graphql@^13.4.1` on Node 20+ and import any module that transitively loads `external.utils.js` (e.g., via `@FilterableField`).

**Comment by abrenoch** [comment]
Can confirm, here is the fix I found to be working for me with `yarn`:

`package.json`:
```
  "scripts": {
    ...
    "postinstall": "patch-package",
    ...
  },
```

New file: `patches/@ptc-org+nestjs-query-graphql+9.4.0.patch`
```
diff --git a/node_modules/@ptc-org/nestjs-query-graphql/src/common/external.utils.js b/node_modules/@ptc-org/nestjs-query-graphql/src/common/external.utils.js
index 1b4ee1b..d00a94b 100644
--- a/node_modules/@ptc-org/nestjs-query-graphql/src/common/external.utils.js
+++ b/node_modules/@ptc-org/nestjs-query-graphql/src/common/external.utils.js
@@ -5,7 +5,7 @@ exports.getGraphqlObjectMetadata = getGraphqlObjectMetadata;
 exports.getGraphqlObjectName = getGraphqlObjectName;
 exports.getGraphqlEnumMetadata = getGraphqlEnumMetadata;
 const graphql_1 = require("@nestjs/graphql");
-const lazy_metadata_storage_1 = require("@nestjs/graphql/dist/schema-builder/storages/lazy-metadata.storage");
+const lazy_metadata_storage_1 = require("@nestjs/graphql/dist/schema-builder/storages/lazy-metadata.storage.js");
 const type_errors_1 = require("../types/type.errors");
 /**
  * @internal
```

What a strange problem

**Comment by TriPSs** [comment]
Think this should be fixed now.
